version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: python manage.py test
  build-and-push-dockerhub:
    docker:
       - image: cimg/python:3.11.1
    steps:
      - checkout
      - setup_remote_docker:
         docker_layer_caching: true
      - run:
         name: Build Docker image
         command: docker build -t docker-oc-lettings:0.1 .
      - run:
         name: Login to DockerHub
         command: docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
      - run:
         name: push Docker image
         command: docker push $DOCKERHUB_USERNAME/oc-lettings:CC

workflows:
  test:
    jobs:
      - test
      - build-and-push-dockerhub
